version: '3.8'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
    - ./ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: bugfinder-backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434   # ← THIS IS THE LINE YOU ADD
    depends_on:
      - ollama
    restart: always

  frontend:
    build: ./frontend
    container_name: bugfinder-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
